---
all:
  children:
    proxy:

proxy:
  hosts:
    prod-nginx-01:
      ansible_host: 127.0.0.1
      ansible_port: 2222
      ansible_ssh_private_key_file: .vagrant/machines/prod-nginx-01/virtualbox/private_key
    prod-nginx-02:
      ansible_host: 127.0.0.1
      ansible_port: 2200
      ansible_ssh_private_key_file: .vagrant/machines/prod-nginx-02/virtualbox/private_key