---
# tasks file for install-prometheus-server
- name: Add Prometheus user
  user:
    name: prometheus
    comment: Prometheus server user
    shell: /bin/false

- name: Check that the somefile exists
  stat:
    path: /tmp/prometheus-{{ version }}.linux-amd64.tar.gz
  register: stat_result

- name: Download prometheus
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v{{ version }}/prometheus-{{ version }}.linux-amd64.tar.gz
    dest: /tmp/
  when: stat_result.stat.exists == False

- name: Extract prometheus
  unarchive:
    src: /tmp/prometheus-{{ version }}.linux-amd64.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Move prometheus folder
  shell: mv prometheus /usr/local/bin/
  args:
    chdir: /tmp/prometheus-{{ version }}.linux-amd64

- name: Create a directory /etc/prometheus/ if it does not exist
  file:
    path: /etc/prometheus/
    state: directory

- name: Copy prometheus.yml
  shell: cp prometheus.yml /etc/prometheus/
  args:
    chdir: /tmp/prometheus-{{ version }}.linux-amd64

- name: Recursively change ownership of a directory /etc/prometheus/
  file:
    path: /etc/prometheus/
    state: directory
    recurse: yes
    owner: prometheus
    group: prometheus

- name: Create a directory /var/lib/prometheus if it does not exist
  file:
    path: /var/lib/prometheus
    state: directory
    owner: prometheus
    group: prometheus

- name: Keys for start Prometheus
  template:
    dest: /etc/sysconfig/prometheus
    src: templates/prometheus.j2

- name: Create systemd service
  template:
    dest: /usr/lib/systemd/system/prometheus.service
    src: templates/prometheus.service.j2
  notify:
    - daemon reload
    - start prometheus
    - restart prometheus

- name: Create systemd service
  template:
    dest: /etc/prometheus/prometheus.yml
    src: templates/prometheus.yml.j2
  notify:
    - restart prometheus