---
- name: Check that the somefile exists
  stat:
    path: /tmp/node_exporter-{{ version }}.linux-amd64.tar.gz
  register: stat_result
  
- name: Download prometheus
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v{{ version }}/node_exporter-{{ version }}.linux-amd64.tar.gz
    dest: /tmp/
  when: stat_result.stat.exists == False

- name: Extract prometheus
  unarchive:
    src: /tmp/node_exporter-{{ version }}.linux-amd64.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Move node-exporter
  shell: mv node_exporter /usr/local/bin/
  args:
    chdir: /tmp/node_exporter-{{ version }}.linux-amd64

- name: Keys for start node_exporter
  template:
    dest: /etc/sysconfig/node_exporter
    src: templates/node_exporter.j2

- name: Create systemd service
  template:
    dest: /usr/lib/systemd/system/node_exporter.service
    src: templates/node_exporter.service.j2
  notify:
    - daemon reload
    - start node_exporter
    - restart node_exporter