# -*- mode: ruby -*-
# vi: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

#MACHINES = {
#  :server => {
#        :box_name => "centos/7",
#        :ip_addr => '192.168.50.10',
#    :disks => {
#        :sata1 => {
#            :dfile => './sata1.vdi',
#            :size => 10240,
#            :port => 1
#        }
#      }
#    }
#  }
#MACHINES = {
#  :client => {
#        :box_name => "centos/7",
#        :ip_addr => '192.168.50.11',
#      :disks => {
#          :sata1 => {
#              :dfile => './sata1.vdi',
#              :size => 10240,
#              :port => 1
#                    }
#                }
#              }
#    }
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.box_check_update = false

  config.vm.define "server" do |server|
    server.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "net1"
    server.vm.hostname = "server"
    server.vm.provision "shell", path: "server_script.sh"
  end

  config.vm.define "client" do |client|
    client.vm.network "private_network", ip: "192.168.50.11", virtualbox__intnet: "net1"
    client.vm.hostname = "client"
    client.vm.provision "shell", path: "client_script.sh"
  end
end