---
# handlers file for install-node-exporter
- name: daemon reload
  systemd:
    daemon_reload: yes

- name: start node_exporter
  systemd:
      name: node_exporter
      state: started
      enabled: yes

- name: restart node_exporter
  systemd:
    name: node_exporter
    state: restarted
    enabled: yes